# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/bootstrap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import base_pb2 as api_dot_base__pb2
from api import cds_pb2 as api_dot_cds__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/bootstrap.proto',
  package='envoy.api.v2',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x61pi/bootstrap.proto\x12\x0c\x65nvoy.api.v2\x1a\x0e\x61pi/base.proto\x1a\rapi/cds.proto\"\xc0\x01\n\tBootstrap\x12 \n\x04node\x18\x01 \x01(\x0b\x32\x12.envoy.api.v2.Node\x12.\n\nlds_config\x18\x02 \x01(\x0b\x32\x1a.envoy.api.v2.ConfigSource\x12.\n\ncds_config\x18\x03 \x01(\x0b\x32\x1a.envoy.api.v2.ConfigSource\x12\x31\n\x12\x62ootstrap_clusters\x18\x04 \x03(\x0b\x32\x15.envoy.api.v2.Clusterb\x06proto3')
  ,
  dependencies=[api_dot_base__pb2.DESCRIPTOR,api_dot_cds__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BOOTSTRAP = _descriptor.Descriptor(
  name='Bootstrap',
  full_name='envoy.api.v2.Bootstrap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='envoy.api.v2.Bootstrap.node', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lds_config', full_name='envoy.api.v2.Bootstrap.lds_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cds_config', full_name='envoy.api.v2.Bootstrap.cds_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bootstrap_clusters', full_name='envoy.api.v2.Bootstrap.bootstrap_clusters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=261,
)

_BOOTSTRAP.fields_by_name['node'].message_type = api_dot_base__pb2._NODE
_BOOTSTRAP.fields_by_name['lds_config'].message_type = api_dot_base__pb2._CONFIGSOURCE
_BOOTSTRAP.fields_by_name['cds_config'].message_type = api_dot_base__pb2._CONFIGSOURCE
_BOOTSTRAP.fields_by_name['bootstrap_clusters'].message_type = api_dot_cds__pb2._CLUSTER
DESCRIPTOR.message_types_by_name['Bootstrap'] = _BOOTSTRAP

Bootstrap = _reflection.GeneratedProtocolMessageType('Bootstrap', (_message.Message,), dict(
  DESCRIPTOR = _BOOTSTRAP,
  __module__ = 'api.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:envoy.api.v2.Bootstrap)
  ))
_sym_db.RegisterMessage(Bootstrap)


# @@protoc_insertion_point(module_scope)
