# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/health_check.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/health_check.proto',
  package='envoy.api.v2',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x61pi/health_check.proto\x12\x0c\x65nvoy.api.v2\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd8\x06\n\x0bHealthCheck\x12*\n\x07timeout\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12+\n\x08interval\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x32\n\x0finterval_jitter\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x39\n\x13unhealthy_threshold\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12\x37\n\x11healthy_threshold\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12.\n\x08\x61lt_port\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12\x34\n\x10reuse_connection\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x46\n\x11http_health_check\x18\x08 \x01(\x0b\x32).envoy.api.v2.HealthCheck.HttpHealthCheckH\x00\x12\x44\n\x10tcp_health_check\x18\t \x01(\x0b\x32(.envoy.api.v2.HealthCheck.TcpHealthCheckH\x00\x1a\x36\n\x07Payload\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\x10\n\x06\x62inary\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\x1a\x92\x01\n\x0fHttpHealthCheck\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12/\n\x04send\x18\x03 \x01(\x0b\x32!.envoy.api.v2.HealthCheck.Payload\x12\x32\n\x07receive\x18\x04 \x01(\x0b\x32!.envoy.api.v2.HealthCheck.Payload\x1au\n\x0eTcpHealthCheck\x12/\n\x04send\x18\x01 \x01(\x0b\x32!.envoy.api.v2.HealthCheck.Payload\x12\x32\n\x07receive\x18\x02 \x01(\x0b\x32!.envoy.api.v2.HealthCheck.PayloadB\x10\n\x0ehealth_checker*R\n\x0cHealthStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07HEALTHY\x10\x01\x12\r\n\tUNHEALTHY\x10\x02\x12\x0c\n\x08\x44RAINING\x10\x03\x12\x0b\n\x07TIMEOUT\x10\x04\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_HEALTHSTATUS = _descriptor.EnumDescriptor(
  name='HealthStatus',
  full_name='envoy.api.v2.HealthStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEALTHY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNHEALTHY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAINING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=963,
  serialized_end=1045,
)
_sym_db.RegisterEnumDescriptor(_HEALTHSTATUS)

HealthStatus = enum_type_wrapper.EnumTypeWrapper(_HEALTHSTATUS)
UNKNOWN = 0
HEALTHY = 1
UNHEALTHY = 2
DRAINING = 3
TIMEOUT = 4



_HEALTHCHECK_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='envoy.api.v2.HealthCheck.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='envoy.api.v2.HealthCheck.Payload.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binary', full_name='envoy.api.v2.HealthCheck.Payload.binary', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='envoy.api.v2.HealthCheck.Payload.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=621,
  serialized_end=675,
)

_HEALTHCHECK_HTTPHEALTHCHECK = _descriptor.Descriptor(
  name='HttpHealthCheck',
  full_name='envoy.api.v2.HealthCheck.HttpHealthCheck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='envoy.api.v2.HealthCheck.HttpHealthCheck.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='envoy.api.v2.HealthCheck.HttpHealthCheck.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='send', full_name='envoy.api.v2.HealthCheck.HttpHealthCheck.send', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receive', full_name='envoy.api.v2.HealthCheck.HttpHealthCheck.receive', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=678,
  serialized_end=824,
)

_HEALTHCHECK_TCPHEALTHCHECK = _descriptor.Descriptor(
  name='TcpHealthCheck',
  full_name='envoy.api.v2.HealthCheck.TcpHealthCheck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send', full_name='envoy.api.v2.HealthCheck.TcpHealthCheck.send', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receive', full_name='envoy.api.v2.HealthCheck.TcpHealthCheck.receive', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=826,
  serialized_end=943,
)

_HEALTHCHECK = _descriptor.Descriptor(
  name='HealthCheck',
  full_name='envoy.api.v2.HealthCheck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeout', full_name='envoy.api.v2.HealthCheck.timeout', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval', full_name='envoy.api.v2.HealthCheck.interval', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval_jitter', full_name='envoy.api.v2.HealthCheck.interval_jitter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unhealthy_threshold', full_name='envoy.api.v2.HealthCheck.unhealthy_threshold', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='healthy_threshold', full_name='envoy.api.v2.HealthCheck.healthy_threshold', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alt_port', full_name='envoy.api.v2.HealthCheck.alt_port', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reuse_connection', full_name='envoy.api.v2.HealthCheck.reuse_connection', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='http_health_check', full_name='envoy.api.v2.HealthCheck.http_health_check', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tcp_health_check', full_name='envoy.api.v2.HealthCheck.tcp_health_check', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HEALTHCHECK_PAYLOAD, _HEALTHCHECK_HTTPHEALTHCHECK, _HEALTHCHECK_TCPHEALTHCHECK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='health_checker', full_name='envoy.api.v2.HealthCheck.health_checker',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=105,
  serialized_end=961,
)

_HEALTHCHECK_PAYLOAD.containing_type = _HEALTHCHECK
_HEALTHCHECK_PAYLOAD.oneofs_by_name['payload'].fields.append(
  _HEALTHCHECK_PAYLOAD.fields_by_name['text'])
_HEALTHCHECK_PAYLOAD.fields_by_name['text'].containing_oneof = _HEALTHCHECK_PAYLOAD.oneofs_by_name['payload']
_HEALTHCHECK_PAYLOAD.oneofs_by_name['payload'].fields.append(
  _HEALTHCHECK_PAYLOAD.fields_by_name['binary'])
_HEALTHCHECK_PAYLOAD.fields_by_name['binary'].containing_oneof = _HEALTHCHECK_PAYLOAD.oneofs_by_name['payload']
_HEALTHCHECK_HTTPHEALTHCHECK.fields_by_name['send'].message_type = _HEALTHCHECK_PAYLOAD
_HEALTHCHECK_HTTPHEALTHCHECK.fields_by_name['receive'].message_type = _HEALTHCHECK_PAYLOAD
_HEALTHCHECK_HTTPHEALTHCHECK.containing_type = _HEALTHCHECK
_HEALTHCHECK_TCPHEALTHCHECK.fields_by_name['send'].message_type = _HEALTHCHECK_PAYLOAD
_HEALTHCHECK_TCPHEALTHCHECK.fields_by_name['receive'].message_type = _HEALTHCHECK_PAYLOAD
_HEALTHCHECK_TCPHEALTHCHECK.containing_type = _HEALTHCHECK
_HEALTHCHECK.fields_by_name['timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_HEALTHCHECK.fields_by_name['interval'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_HEALTHCHECK.fields_by_name['interval_jitter'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_HEALTHCHECK.fields_by_name['unhealthy_threshold'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_HEALTHCHECK.fields_by_name['healthy_threshold'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_HEALTHCHECK.fields_by_name['alt_port'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_HEALTHCHECK.fields_by_name['reuse_connection'].message_type = google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE
_HEALTHCHECK.fields_by_name['http_health_check'].message_type = _HEALTHCHECK_HTTPHEALTHCHECK
_HEALTHCHECK.fields_by_name['tcp_health_check'].message_type = _HEALTHCHECK_TCPHEALTHCHECK
_HEALTHCHECK.oneofs_by_name['health_checker'].fields.append(
  _HEALTHCHECK.fields_by_name['http_health_check'])
_HEALTHCHECK.fields_by_name['http_health_check'].containing_oneof = _HEALTHCHECK.oneofs_by_name['health_checker']
_HEALTHCHECK.oneofs_by_name['health_checker'].fields.append(
  _HEALTHCHECK.fields_by_name['tcp_health_check'])
_HEALTHCHECK.fields_by_name['tcp_health_check'].containing_oneof = _HEALTHCHECK.oneofs_by_name['health_checker']
DESCRIPTOR.message_types_by_name['HealthCheck'] = _HEALTHCHECK
DESCRIPTOR.enum_types_by_name['HealthStatus'] = _HEALTHSTATUS

HealthCheck = _reflection.GeneratedProtocolMessageType('HealthCheck', (_message.Message,), dict(

  Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
    DESCRIPTOR = _HEALTHCHECK_PAYLOAD,
    __module__ = 'api.health_check_pb2'
    # @@protoc_insertion_point(class_scope:envoy.api.v2.HealthCheck.Payload)
    ))
  ,

  HttpHealthCheck = _reflection.GeneratedProtocolMessageType('HttpHealthCheck', (_message.Message,), dict(
    DESCRIPTOR = _HEALTHCHECK_HTTPHEALTHCHECK,
    __module__ = 'api.health_check_pb2'
    # @@protoc_insertion_point(class_scope:envoy.api.v2.HealthCheck.HttpHealthCheck)
    ))
  ,

  TcpHealthCheck = _reflection.GeneratedProtocolMessageType('TcpHealthCheck', (_message.Message,), dict(
    DESCRIPTOR = _HEALTHCHECK_TCPHEALTHCHECK,
    __module__ = 'api.health_check_pb2'
    # @@protoc_insertion_point(class_scope:envoy.api.v2.HealthCheck.TcpHealthCheck)
    ))
  ,
  DESCRIPTOR = _HEALTHCHECK,
  __module__ = 'api.health_check_pb2'
  # @@protoc_insertion_point(class_scope:envoy.api.v2.HealthCheck)
  ))
_sym_db.RegisterMessage(HealthCheck)
_sym_db.RegisterMessage(HealthCheck.Payload)
_sym_db.RegisterMessage(HealthCheck.HttpHealthCheck)
_sym_db.RegisterMessage(HealthCheck.TcpHealthCheck)


# @@protoc_insertion_point(module_scope)
