kind: ConfigMap
metadata:
  name: istio-inject
  namespace: {{ .Values.istioNamespace }}
apiVersion: v1
data:
  config: |
    policy: enabled
    template: |-
      initContainers:
      - name: istio-init
        image: {{ .Values.istioHub }}/proxy_init:{{ .Values.istioTag }}
        args:
        - "-p"
        - {{"{{"}} .MeshConfig.ProxyListenPort {{"}}"}}
        - "-u"
        - 1337
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          {{ if .Values.sidecarDebug }}
          privileged: true
          {{ end }}
        restartPolicy: Always
        {{ if .Values.sidecarCoreDump }}
      - args:
        - -c
        - sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t && ulimit -c
          unlimited
        command:
        - /bin/sh
        image: alpine
        imagePullPolicy: IfNotPresent
        name: enable-core-dump
        resources: {}
        securityContext:
          privileged: true
        {{ end }}
      containers:
      - name: istio-proxy
        {{ if .Values.sidecarDebug }}
        image: {{ .Values.istioHub }}/{{ .Values.proxyImage}}:{{ .Values.istioTag }}
        {{ else }} 
        image: {{ .Values.istioHub }}/proxy_debug:{{ .Values.istioTag }}
        {{ end }}
        args:
        - proxy
        - sidecar
        - --configPath
        - {{"{{"}} .ProxyConfig.ConfigPath {{"}}"}}
        - --binaryPath
        - {{"{{"}} .ProxyConfig.BinaryPath {{"}}"}}
        - --serviceCluster
        {{"{{"}} if ne "" (index .ObjectMeta.Labels "app") -}}
        - {{"{{"}} index .ObjectMeta.Labels "app" {{"}}"}}
        {{"{{"}} else -}}
        - "istio-proxy"
        {{"{{"}} end -}}
        - --drainDuration
        - 2s
        - --parentShutdownDuration
        - 3s
        - --discoveryAddress
        - {{"{{"}} .ProxyConfig.DiscoveryAddress {{"}}"}}
        - --discoveryRefreshDelay
        - {{ .Values.discoveryRefreshDelay }}
        {{ if .Values.enableTracing }}
        - --zipkinAddress
        - {{"{{ .ProxyConfig.ZipkinAddress }}"}}
        {{ end }}
        - --connectTimeout
        - 1s
        {{ if .Values.enableEnvoyStatsd }}
        - --statsdUdpAddress
        - {{"{{ .ProxyConfig.StatsdUdpAddress }}"}}
        {{ end }}
        - --proxyAdminPort
        - {{"{{ .ProxyConfig.ProxyAdminPort }}"}}
        - --controlPlaneAuthPolicy
        - {{"{{ .ProxyConfig.ControlPlaneAuthPolicy }}"}}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: IfNotPresent
        securityContext:
            {{ if .Values.sidecarDebug }}
            privileged: true
            readOnlyRootFilesystem: false
            {{ else }}
            privileged: false
            readOnlyRootFilesystem: true
            {{ end }}
            runAsUser: 1337
        restartPolicy: Always
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          {{"{{"}} if eq .Spec.ServiceAccountName "" -{{"}}"}}
          secretName: istio.default
          {{"{{ else -}}"}}
          secretName: {{"{{"}} printf "istio.%s" .Spec.ServiceAccountName {{"}}"}}
          {{"{{ end -}}"}}
