// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source/common/ratelimit/ratelimit.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "source/common/ratelimit/ratelimit.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {
namespace lyft {
namespace ratelimit {
class RateLimitRequestDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RateLimitRequest>
     _instance;
} _RateLimitRequest_default_instance_;
class RateLimitDescriptor_EntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RateLimitDescriptor_Entry>
     _instance;
} _RateLimitDescriptor_Entry_default_instance_;
class RateLimitDescriptorDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RateLimitDescriptor>
     _instance;
} _RateLimitDescriptor_default_instance_;
class RateLimitDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RateLimit>
     _instance;
} _RateLimit_default_instance_;
class RateLimitResponse_DescriptorStatusDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RateLimitResponse_DescriptorStatus>
     _instance;
} _RateLimitResponse_DescriptorStatus_default_instance_;
class RateLimitResponseDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RateLimitResponse>
     _instance;
} _RateLimitResponse_default_instance_;

namespace protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[6];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitRequest, domain_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitRequest, descriptors_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitDescriptor_Entry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitDescriptor_Entry, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitDescriptor_Entry, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitDescriptor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitDescriptor, entries_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimit, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimit, requests_per_unit_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimit, unit_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitResponse_DescriptorStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitResponse_DescriptorStatus, code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitResponse_DescriptorStatus, current_limit_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitResponse_DescriptorStatus, limit_remaining_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitResponse, overall_code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RateLimitResponse, statuses_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(RateLimitRequest)},
  { 7, -1, sizeof(RateLimitDescriptor_Entry)},
  { 14, -1, sizeof(RateLimitDescriptor)},
  { 20, -1, sizeof(RateLimit)},
  { 27, -1, sizeof(RateLimitResponse_DescriptorStatus)},
  { 35, -1, sizeof(RateLimitResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_RateLimitRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_RateLimitDescriptor_Entry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_RateLimitDescriptor_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_RateLimit_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_RateLimitResponse_DescriptorStatus_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_RateLimitResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "source/common/ratelimit/ratelimit.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _RateLimitRequest_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_RateLimitRequest_default_instance_);_RateLimitDescriptor_Entry_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_RateLimitDescriptor_Entry_default_instance_);_RateLimitDescriptor_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_RateLimitDescriptor_default_instance_);_RateLimit_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_RateLimit_default_instance_);_RateLimitResponse_DescriptorStatus_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_RateLimitResponse_DescriptorStatus_default_instance_);_RateLimitResponse_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_RateLimitResponse_default_instance_);_RateLimitResponse_DescriptorStatus_default_instance_._instance.get_mutable()->current_limit_ = const_cast< ::pb::lyft::ratelimit::RateLimit*>(
      ::pb::lyft::ratelimit::RateLimit::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\'source/common/ratelimit/ratelimit.prot"
      "o\022\021pb.lyft.ratelimit\"_\n\020RateLimitRequest"
      "\022\016\n\006domain\030\001 \001(\t\022;\n\013descriptors\030\002 \003(\0132&."
      "pb.lyft.ratelimit.RateLimitDescriptor\"y\n"
      "\023RateLimitDescriptor\022=\n\007entries\030\001 \003(\0132,."
      "pb.lyft.ratelimit.RateLimitDescriptor.En"
      "try\032#\n\005Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t"
      "\"\227\001\n\tRateLimit\022\031\n\021requests_per_unit\030\001 \001("
      "\r\022/\n\004unit\030\002 \001(\0162!.pb.lyft.ratelimit.Rate"
      "Limit.Unit\">\n\004Unit\022\013\n\007UNKNOWN\020\000\022\n\n\006SECON"
      "D\020\001\022\n\n\006MINUTE\020\002\022\010\n\004HOUR\020\003\022\007\n\003DAY\020\004\"\346\002\n\021R"
      "ateLimitResponse\022\?\n\014overall_code\030\001 \001(\0162)"
      ".pb.lyft.ratelimit.RateLimitResponse.Cod"
      "e\022G\n\010statuses\030\002 \003(\01325.pb.lyft.ratelimit."
      "RateLimitResponse.DescriptorStatus\032\231\001\n\020D"
      "escriptorStatus\0227\n\004code\030\001 \001(\0162).pb.lyft."
      "ratelimit.RateLimitResponse.Code\0223\n\rcurr"
      "ent_limit\030\002 \001(\0132\034.pb.lyft.ratelimit.Rate"
      "Limit\022\027\n\017limit_remaining\030\003 \001(\r\"+\n\004Code\022\013"
      "\n\007UNKNOWN\020\000\022\006\n\002OK\020\001\022\016\n\nOVER_LIMIT\020\0022r\n\020R"
      "ateLimitService\022^\n\017ShouldRateLimit\022#.pb."
      "lyft.ratelimit.RateLimitRequest\032$.pb.lyf"
      "t.ratelimit.RateLimitResponse\"\000B\013Z\tratel"
      "imitb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 932);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "source/common/ratelimit/ratelimit.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto

const ::google::protobuf::EnumDescriptor* RateLimit_Unit_descriptor() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_enum_descriptors[0];
}
bool RateLimit_Unit_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const RateLimit_Unit RateLimit::UNKNOWN;
const RateLimit_Unit RateLimit::SECOND;
const RateLimit_Unit RateLimit::MINUTE;
const RateLimit_Unit RateLimit::HOUR;
const RateLimit_Unit RateLimit::DAY;
const RateLimit_Unit RateLimit::Unit_MIN;
const RateLimit_Unit RateLimit::Unit_MAX;
const int RateLimit::Unit_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* RateLimitResponse_Code_descriptor() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_enum_descriptors[1];
}
bool RateLimitResponse_Code_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const RateLimitResponse_Code RateLimitResponse::UNKNOWN;
const RateLimitResponse_Code RateLimitResponse::OK;
const RateLimitResponse_Code RateLimitResponse::OVER_LIMIT;
const RateLimitResponse_Code RateLimitResponse::Code_MIN;
const RateLimitResponse_Code RateLimitResponse::Code_MAX;
const int RateLimitResponse::Code_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RateLimitRequest::kDomainFieldNumber;
const int RateLimitRequest::kDescriptorsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RateLimitRequest::RateLimitRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.lyft.ratelimit.RateLimitRequest)
}
RateLimitRequest::RateLimitRequest(const RateLimitRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      descriptors_(from.descriptors_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  domain_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.domain().size() > 0) {
    domain_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.domain_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.lyft.ratelimit.RateLimitRequest)
}

void RateLimitRequest::SharedCtor() {
  domain_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

RateLimitRequest::~RateLimitRequest() {
  // @@protoc_insertion_point(destructor:pb.lyft.ratelimit.RateLimitRequest)
  SharedDtor();
}

void RateLimitRequest::SharedDtor() {
  domain_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RateLimitRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RateLimitRequest::descriptor() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RateLimitRequest& RateLimitRequest::default_instance() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  return *internal_default_instance();
}

RateLimitRequest* RateLimitRequest::New(::google::protobuf::Arena* arena) const {
  RateLimitRequest* n = new RateLimitRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RateLimitRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.lyft.ratelimit.RateLimitRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  descriptors_.Clear();
  domain_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool RateLimitRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.lyft.ratelimit.RateLimitRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string domain = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_domain()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->domain().data(), static_cast<int>(this->domain().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.lyft.ratelimit.RateLimitRequest.domain"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pb.lyft.ratelimit.RateLimitDescriptor descriptors = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_descriptors()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.lyft.ratelimit.RateLimitRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.lyft.ratelimit.RateLimitRequest)
  return false;
#undef DO_
}

void RateLimitRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.lyft.ratelimit.RateLimitRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string domain = 1;
  if (this->domain().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->domain().data(), static_cast<int>(this->domain().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.lyft.ratelimit.RateLimitRequest.domain");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->domain(), output);
  }

  // repeated .pb.lyft.ratelimit.RateLimitDescriptor descriptors = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->descriptors_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->descriptors(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.lyft.ratelimit.RateLimitRequest)
}

::google::protobuf::uint8* RateLimitRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pb.lyft.ratelimit.RateLimitRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string domain = 1;
  if (this->domain().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->domain().data(), static_cast<int>(this->domain().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.lyft.ratelimit.RateLimitRequest.domain");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->domain(), target);
  }

  // repeated .pb.lyft.ratelimit.RateLimitDescriptor descriptors = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->descriptors_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->descriptors(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.lyft.ratelimit.RateLimitRequest)
  return target;
}

size_t RateLimitRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.lyft.ratelimit.RateLimitRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .pb.lyft.ratelimit.RateLimitDescriptor descriptors = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->descriptors_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->descriptors(static_cast<int>(i)));
    }
  }

  // string domain = 1;
  if (this->domain().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->domain());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RateLimitRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.lyft.ratelimit.RateLimitRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const RateLimitRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RateLimitRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.lyft.ratelimit.RateLimitRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.lyft.ratelimit.RateLimitRequest)
    MergeFrom(*source);
  }
}

void RateLimitRequest::MergeFrom(const RateLimitRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.lyft.ratelimit.RateLimitRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  descriptors_.MergeFrom(from.descriptors_);
  if (from.domain().size() > 0) {

    domain_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.domain_);
  }
}

void RateLimitRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.lyft.ratelimit.RateLimitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RateLimitRequest::CopyFrom(const RateLimitRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.lyft.ratelimit.RateLimitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RateLimitRequest::IsInitialized() const {
  return true;
}

void RateLimitRequest::Swap(RateLimitRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RateLimitRequest::InternalSwap(RateLimitRequest* other) {
  using std::swap;
  descriptors_.InternalSwap(&other->descriptors_);
  domain_.Swap(&other->domain_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RateLimitRequest::GetMetadata() const {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RateLimitRequest

// string domain = 1;
void RateLimitRequest::clear_domain() {
  domain_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& RateLimitRequest::domain() const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitRequest.domain)
  return domain_.GetNoArena();
}
void RateLimitRequest::set_domain(const ::std::string& value) {
  
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.lyft.ratelimit.RateLimitRequest.domain)
}
#if LANG_CXX11
void RateLimitRequest::set_domain(::std::string&& value) {
  
  domain_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.lyft.ratelimit.RateLimitRequest.domain)
}
#endif
void RateLimitRequest::set_domain(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.lyft.ratelimit.RateLimitRequest.domain)
}
void RateLimitRequest::set_domain(const char* value, size_t size) {
  
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.lyft.ratelimit.RateLimitRequest.domain)
}
::std::string* RateLimitRequest::mutable_domain() {
  
  // @@protoc_insertion_point(field_mutable:pb.lyft.ratelimit.RateLimitRequest.domain)
  return domain_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* RateLimitRequest::release_domain() {
  // @@protoc_insertion_point(field_release:pb.lyft.ratelimit.RateLimitRequest.domain)
  
  return domain_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RateLimitRequest::set_allocated_domain(::std::string* domain) {
  if (domain != NULL) {
    
  } else {
    
  }
  domain_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), domain);
  // @@protoc_insertion_point(field_set_allocated:pb.lyft.ratelimit.RateLimitRequest.domain)
}

// repeated .pb.lyft.ratelimit.RateLimitDescriptor descriptors = 2;
int RateLimitRequest::descriptors_size() const {
  return descriptors_.size();
}
void RateLimitRequest::clear_descriptors() {
  descriptors_.Clear();
}
const ::pb::lyft::ratelimit::RateLimitDescriptor& RateLimitRequest::descriptors(int index) const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitRequest.descriptors)
  return descriptors_.Get(index);
}
::pb::lyft::ratelimit::RateLimitDescriptor* RateLimitRequest::mutable_descriptors(int index) {
  // @@protoc_insertion_point(field_mutable:pb.lyft.ratelimit.RateLimitRequest.descriptors)
  return descriptors_.Mutable(index);
}
::pb::lyft::ratelimit::RateLimitDescriptor* RateLimitRequest::add_descriptors() {
  // @@protoc_insertion_point(field_add:pb.lyft.ratelimit.RateLimitRequest.descriptors)
  return descriptors_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::lyft::ratelimit::RateLimitDescriptor >*
RateLimitRequest::mutable_descriptors() {
  // @@protoc_insertion_point(field_mutable_list:pb.lyft.ratelimit.RateLimitRequest.descriptors)
  return &descriptors_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::lyft::ratelimit::RateLimitDescriptor >&
RateLimitRequest::descriptors() const {
  // @@protoc_insertion_point(field_list:pb.lyft.ratelimit.RateLimitRequest.descriptors)
  return descriptors_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RateLimitDescriptor_Entry::kKeyFieldNumber;
const int RateLimitDescriptor_Entry::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RateLimitDescriptor_Entry::RateLimitDescriptor_Entry()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
}
RateLimitDescriptor_Entry::RateLimitDescriptor_Entry(const RateLimitDescriptor_Entry& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
}

void RateLimitDescriptor_Entry::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

RateLimitDescriptor_Entry::~RateLimitDescriptor_Entry() {
  // @@protoc_insertion_point(destructor:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  SharedDtor();
}

void RateLimitDescriptor_Entry::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RateLimitDescriptor_Entry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RateLimitDescriptor_Entry::descriptor() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RateLimitDescriptor_Entry& RateLimitDescriptor_Entry::default_instance() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  return *internal_default_instance();
}

RateLimitDescriptor_Entry* RateLimitDescriptor_Entry::New(::google::protobuf::Arena* arena) const {
  RateLimitDescriptor_Entry* n = new RateLimitDescriptor_Entry;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RateLimitDescriptor_Entry::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool RateLimitDescriptor_Entry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.lyft.ratelimit.RateLimitDescriptor.Entry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), static_cast<int>(this->value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.lyft.ratelimit.RateLimitDescriptor.Entry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  return false;
#undef DO_
}

void RateLimitDescriptor_Entry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.lyft.ratelimit.RateLimitDescriptor.Entry.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.lyft.ratelimit.RateLimitDescriptor.Entry.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
}

::google::protobuf::uint8* RateLimitDescriptor_Entry::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.lyft.ratelimit.RateLimitDescriptor.Entry.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.lyft.ratelimit.RateLimitDescriptor.Entry.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  return target;
}

size_t RateLimitDescriptor_Entry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RateLimitDescriptor_Entry::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  GOOGLE_DCHECK_NE(&from, this);
  const RateLimitDescriptor_Entry* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RateLimitDescriptor_Entry>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
    MergeFrom(*source);
  }
}

void RateLimitDescriptor_Entry::MergeFrom(const RateLimitDescriptor_Entry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void RateLimitDescriptor_Entry::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RateLimitDescriptor_Entry::CopyFrom(const RateLimitDescriptor_Entry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.lyft.ratelimit.RateLimitDescriptor.Entry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RateLimitDescriptor_Entry::IsInitialized() const {
  return true;
}

void RateLimitDescriptor_Entry::Swap(RateLimitDescriptor_Entry* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RateLimitDescriptor_Entry::InternalSwap(RateLimitDescriptor_Entry* other) {
  using std::swap;
  key_.Swap(&other->key_);
  value_.Swap(&other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RateLimitDescriptor_Entry::GetMetadata() const {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RateLimitDescriptor_Entry

// string key = 1;
void RateLimitDescriptor_Entry::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& RateLimitDescriptor_Entry::key() const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitDescriptor.Entry.key)
  return key_.GetNoArena();
}
void RateLimitDescriptor_Entry::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.lyft.ratelimit.RateLimitDescriptor.Entry.key)
}
#if LANG_CXX11
void RateLimitDescriptor_Entry::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.lyft.ratelimit.RateLimitDescriptor.Entry.key)
}
#endif
void RateLimitDescriptor_Entry::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.lyft.ratelimit.RateLimitDescriptor.Entry.key)
}
void RateLimitDescriptor_Entry::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.lyft.ratelimit.RateLimitDescriptor.Entry.key)
}
::std::string* RateLimitDescriptor_Entry::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:pb.lyft.ratelimit.RateLimitDescriptor.Entry.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* RateLimitDescriptor_Entry::release_key() {
  // @@protoc_insertion_point(field_release:pb.lyft.ratelimit.RateLimitDescriptor.Entry.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RateLimitDescriptor_Entry::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:pb.lyft.ratelimit.RateLimitDescriptor.Entry.key)
}

// string value = 2;
void RateLimitDescriptor_Entry::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& RateLimitDescriptor_Entry::value() const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitDescriptor.Entry.value)
  return value_.GetNoArena();
}
void RateLimitDescriptor_Entry::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.lyft.ratelimit.RateLimitDescriptor.Entry.value)
}
#if LANG_CXX11
void RateLimitDescriptor_Entry::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.lyft.ratelimit.RateLimitDescriptor.Entry.value)
}
#endif
void RateLimitDescriptor_Entry::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.lyft.ratelimit.RateLimitDescriptor.Entry.value)
}
void RateLimitDescriptor_Entry::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.lyft.ratelimit.RateLimitDescriptor.Entry.value)
}
::std::string* RateLimitDescriptor_Entry::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:pb.lyft.ratelimit.RateLimitDescriptor.Entry.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* RateLimitDescriptor_Entry::release_value() {
  // @@protoc_insertion_point(field_release:pb.lyft.ratelimit.RateLimitDescriptor.Entry.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RateLimitDescriptor_Entry::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:pb.lyft.ratelimit.RateLimitDescriptor.Entry.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RateLimitDescriptor::kEntriesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RateLimitDescriptor::RateLimitDescriptor()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.lyft.ratelimit.RateLimitDescriptor)
}
RateLimitDescriptor::RateLimitDescriptor(const RateLimitDescriptor& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      entries_(from.entries_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pb.lyft.ratelimit.RateLimitDescriptor)
}

void RateLimitDescriptor::SharedCtor() {
  _cached_size_ = 0;
}

RateLimitDescriptor::~RateLimitDescriptor() {
  // @@protoc_insertion_point(destructor:pb.lyft.ratelimit.RateLimitDescriptor)
  SharedDtor();
}

void RateLimitDescriptor::SharedDtor() {
}

void RateLimitDescriptor::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RateLimitDescriptor::descriptor() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RateLimitDescriptor& RateLimitDescriptor::default_instance() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  return *internal_default_instance();
}

RateLimitDescriptor* RateLimitDescriptor::New(::google::protobuf::Arena* arena) const {
  RateLimitDescriptor* n = new RateLimitDescriptor;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RateLimitDescriptor::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.lyft.ratelimit.RateLimitDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  entries_.Clear();
  _internal_metadata_.Clear();
}

bool RateLimitDescriptor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.lyft.ratelimit.RateLimitDescriptor)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.lyft.ratelimit.RateLimitDescriptor.Entry entries = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_entries()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.lyft.ratelimit.RateLimitDescriptor)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.lyft.ratelimit.RateLimitDescriptor)
  return false;
#undef DO_
}

void RateLimitDescriptor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.lyft.ratelimit.RateLimitDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.lyft.ratelimit.RateLimitDescriptor.Entry entries = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->entries_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->entries(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.lyft.ratelimit.RateLimitDescriptor)
}

::google::protobuf::uint8* RateLimitDescriptor::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pb.lyft.ratelimit.RateLimitDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.lyft.ratelimit.RateLimitDescriptor.Entry entries = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->entries_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->entries(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.lyft.ratelimit.RateLimitDescriptor)
  return target;
}

size_t RateLimitDescriptor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.lyft.ratelimit.RateLimitDescriptor)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .pb.lyft.ratelimit.RateLimitDescriptor.Entry entries = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->entries_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->entries(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RateLimitDescriptor::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.lyft.ratelimit.RateLimitDescriptor)
  GOOGLE_DCHECK_NE(&from, this);
  const RateLimitDescriptor* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RateLimitDescriptor>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.lyft.ratelimit.RateLimitDescriptor)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.lyft.ratelimit.RateLimitDescriptor)
    MergeFrom(*source);
  }
}

void RateLimitDescriptor::MergeFrom(const RateLimitDescriptor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.lyft.ratelimit.RateLimitDescriptor)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  entries_.MergeFrom(from.entries_);
}

void RateLimitDescriptor::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.lyft.ratelimit.RateLimitDescriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RateLimitDescriptor::CopyFrom(const RateLimitDescriptor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.lyft.ratelimit.RateLimitDescriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RateLimitDescriptor::IsInitialized() const {
  return true;
}

void RateLimitDescriptor::Swap(RateLimitDescriptor* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RateLimitDescriptor::InternalSwap(RateLimitDescriptor* other) {
  using std::swap;
  entries_.InternalSwap(&other->entries_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RateLimitDescriptor::GetMetadata() const {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RateLimitDescriptor

// repeated .pb.lyft.ratelimit.RateLimitDescriptor.Entry entries = 1;
int RateLimitDescriptor::entries_size() const {
  return entries_.size();
}
void RateLimitDescriptor::clear_entries() {
  entries_.Clear();
}
const ::pb::lyft::ratelimit::RateLimitDescriptor_Entry& RateLimitDescriptor::entries(int index) const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitDescriptor.entries)
  return entries_.Get(index);
}
::pb::lyft::ratelimit::RateLimitDescriptor_Entry* RateLimitDescriptor::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:pb.lyft.ratelimit.RateLimitDescriptor.entries)
  return entries_.Mutable(index);
}
::pb::lyft::ratelimit::RateLimitDescriptor_Entry* RateLimitDescriptor::add_entries() {
  // @@protoc_insertion_point(field_add:pb.lyft.ratelimit.RateLimitDescriptor.entries)
  return entries_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::lyft::ratelimit::RateLimitDescriptor_Entry >*
RateLimitDescriptor::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:pb.lyft.ratelimit.RateLimitDescriptor.entries)
  return &entries_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::lyft::ratelimit::RateLimitDescriptor_Entry >&
RateLimitDescriptor::entries() const {
  // @@protoc_insertion_point(field_list:pb.lyft.ratelimit.RateLimitDescriptor.entries)
  return entries_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RateLimit::kRequestsPerUnitFieldNumber;
const int RateLimit::kUnitFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RateLimit::RateLimit()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.lyft.ratelimit.RateLimit)
}
RateLimit::RateLimit(const RateLimit& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&requests_per_unit_, &from.requests_per_unit_,
    static_cast<size_t>(reinterpret_cast<char*>(&unit_) -
    reinterpret_cast<char*>(&requests_per_unit_)) + sizeof(unit_));
  // @@protoc_insertion_point(copy_constructor:pb.lyft.ratelimit.RateLimit)
}

void RateLimit::SharedCtor() {
  ::memset(&requests_per_unit_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&unit_) -
      reinterpret_cast<char*>(&requests_per_unit_)) + sizeof(unit_));
  _cached_size_ = 0;
}

RateLimit::~RateLimit() {
  // @@protoc_insertion_point(destructor:pb.lyft.ratelimit.RateLimit)
  SharedDtor();
}

void RateLimit::SharedDtor() {
}

void RateLimit::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RateLimit::descriptor() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RateLimit& RateLimit::default_instance() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  return *internal_default_instance();
}

RateLimit* RateLimit::New(::google::protobuf::Arena* arena) const {
  RateLimit* n = new RateLimit;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RateLimit::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.lyft.ratelimit.RateLimit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&requests_per_unit_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&unit_) -
      reinterpret_cast<char*>(&requests_per_unit_)) + sizeof(unit_));
  _internal_metadata_.Clear();
}

bool RateLimit::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.lyft.ratelimit.RateLimit)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 requests_per_unit = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &requests_per_unit_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .pb.lyft.ratelimit.RateLimit.Unit unit = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_unit(static_cast< ::pb::lyft::ratelimit::RateLimit_Unit >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.lyft.ratelimit.RateLimit)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.lyft.ratelimit.RateLimit)
  return false;
#undef DO_
}

void RateLimit::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.lyft.ratelimit.RateLimit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 requests_per_unit = 1;
  if (this->requests_per_unit() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->requests_per_unit(), output);
  }

  // .pb.lyft.ratelimit.RateLimit.Unit unit = 2;
  if (this->unit() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->unit(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.lyft.ratelimit.RateLimit)
}

::google::protobuf::uint8* RateLimit::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pb.lyft.ratelimit.RateLimit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 requests_per_unit = 1;
  if (this->requests_per_unit() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->requests_per_unit(), target);
  }

  // .pb.lyft.ratelimit.RateLimit.Unit unit = 2;
  if (this->unit() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->unit(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.lyft.ratelimit.RateLimit)
  return target;
}

size_t RateLimit::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.lyft.ratelimit.RateLimit)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 requests_per_unit = 1;
  if (this->requests_per_unit() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->requests_per_unit());
  }

  // .pb.lyft.ratelimit.RateLimit.Unit unit = 2;
  if (this->unit() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->unit());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RateLimit::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.lyft.ratelimit.RateLimit)
  GOOGLE_DCHECK_NE(&from, this);
  const RateLimit* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RateLimit>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.lyft.ratelimit.RateLimit)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.lyft.ratelimit.RateLimit)
    MergeFrom(*source);
  }
}

void RateLimit::MergeFrom(const RateLimit& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.lyft.ratelimit.RateLimit)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.requests_per_unit() != 0) {
    set_requests_per_unit(from.requests_per_unit());
  }
  if (from.unit() != 0) {
    set_unit(from.unit());
  }
}

void RateLimit::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.lyft.ratelimit.RateLimit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RateLimit::CopyFrom(const RateLimit& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.lyft.ratelimit.RateLimit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RateLimit::IsInitialized() const {
  return true;
}

void RateLimit::Swap(RateLimit* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RateLimit::InternalSwap(RateLimit* other) {
  using std::swap;
  swap(requests_per_unit_, other->requests_per_unit_);
  swap(unit_, other->unit_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RateLimit::GetMetadata() const {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RateLimit

// uint32 requests_per_unit = 1;
void RateLimit::clear_requests_per_unit() {
  requests_per_unit_ = 0u;
}
::google::protobuf::uint32 RateLimit::requests_per_unit() const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimit.requests_per_unit)
  return requests_per_unit_;
}
void RateLimit::set_requests_per_unit(::google::protobuf::uint32 value) {
  
  requests_per_unit_ = value;
  // @@protoc_insertion_point(field_set:pb.lyft.ratelimit.RateLimit.requests_per_unit)
}

// .pb.lyft.ratelimit.RateLimit.Unit unit = 2;
void RateLimit::clear_unit() {
  unit_ = 0;
}
::pb::lyft::ratelimit::RateLimit_Unit RateLimit::unit() const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimit.unit)
  return static_cast< ::pb::lyft::ratelimit::RateLimit_Unit >(unit_);
}
void RateLimit::set_unit(::pb::lyft::ratelimit::RateLimit_Unit value) {
  
  unit_ = value;
  // @@protoc_insertion_point(field_set:pb.lyft.ratelimit.RateLimit.unit)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RateLimitResponse_DescriptorStatus::kCodeFieldNumber;
const int RateLimitResponse_DescriptorStatus::kCurrentLimitFieldNumber;
const int RateLimitResponse_DescriptorStatus::kLimitRemainingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RateLimitResponse_DescriptorStatus::RateLimitResponse_DescriptorStatus()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
}
RateLimitResponse_DescriptorStatus::RateLimitResponse_DescriptorStatus(const RateLimitResponse_DescriptorStatus& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_current_limit()) {
    current_limit_ = new ::pb::lyft::ratelimit::RateLimit(*from.current_limit_);
  } else {
    current_limit_ = NULL;
  }
  ::memcpy(&code_, &from.code_,
    static_cast<size_t>(reinterpret_cast<char*>(&limit_remaining_) -
    reinterpret_cast<char*>(&code_)) + sizeof(limit_remaining_));
  // @@protoc_insertion_point(copy_constructor:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
}

void RateLimitResponse_DescriptorStatus::SharedCtor() {
  ::memset(&current_limit_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&limit_remaining_) -
      reinterpret_cast<char*>(&current_limit_)) + sizeof(limit_remaining_));
  _cached_size_ = 0;
}

RateLimitResponse_DescriptorStatus::~RateLimitResponse_DescriptorStatus() {
  // @@protoc_insertion_point(destructor:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  SharedDtor();
}

void RateLimitResponse_DescriptorStatus::SharedDtor() {
  if (this != internal_default_instance()) delete current_limit_;
}

void RateLimitResponse_DescriptorStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RateLimitResponse_DescriptorStatus::descriptor() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RateLimitResponse_DescriptorStatus& RateLimitResponse_DescriptorStatus::default_instance() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  return *internal_default_instance();
}

RateLimitResponse_DescriptorStatus* RateLimitResponse_DescriptorStatus::New(::google::protobuf::Arena* arena) const {
  RateLimitResponse_DescriptorStatus* n = new RateLimitResponse_DescriptorStatus;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RateLimitResponse_DescriptorStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && current_limit_ != NULL) {
    delete current_limit_;
  }
  current_limit_ = NULL;
  ::memset(&code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&limit_remaining_) -
      reinterpret_cast<char*>(&code_)) + sizeof(limit_remaining_));
  _internal_metadata_.Clear();
}

bool RateLimitResponse_DescriptorStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .pb.lyft.ratelimit.RateLimitResponse.Code code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_code(static_cast< ::pb::lyft::ratelimit::RateLimitResponse_Code >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .pb.lyft.ratelimit.RateLimit current_limit = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_current_limit()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 limit_remaining = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &limit_remaining_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  return false;
#undef DO_
}

void RateLimitResponse_DescriptorStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .pb.lyft.ratelimit.RateLimitResponse.Code code = 1;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->code(), output);
  }

  // .pb.lyft.ratelimit.RateLimit current_limit = 2;
  if (this->has_current_limit()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->current_limit_, output);
  }

  // uint32 limit_remaining = 3;
  if (this->limit_remaining() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->limit_remaining(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
}

::google::protobuf::uint8* RateLimitResponse_DescriptorStatus::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .pb.lyft.ratelimit.RateLimitResponse.Code code = 1;
  if (this->code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->code(), target);
  }

  // .pb.lyft.ratelimit.RateLimit current_limit = 2;
  if (this->has_current_limit()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->current_limit_, deterministic, target);
  }

  // uint32 limit_remaining = 3;
  if (this->limit_remaining() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->limit_remaining(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  return target;
}

size_t RateLimitResponse_DescriptorStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .pb.lyft.ratelimit.RateLimit current_limit = 2;
  if (this->has_current_limit()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->current_limit_);
  }

  // .pb.lyft.ratelimit.RateLimitResponse.Code code = 1;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->code());
  }

  // uint32 limit_remaining = 3;
  if (this->limit_remaining() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->limit_remaining());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RateLimitResponse_DescriptorStatus::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  GOOGLE_DCHECK_NE(&from, this);
  const RateLimitResponse_DescriptorStatus* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RateLimitResponse_DescriptorStatus>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
    MergeFrom(*source);
  }
}

void RateLimitResponse_DescriptorStatus::MergeFrom(const RateLimitResponse_DescriptorStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_current_limit()) {
    mutable_current_limit()->::pb::lyft::ratelimit::RateLimit::MergeFrom(from.current_limit());
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
  if (from.limit_remaining() != 0) {
    set_limit_remaining(from.limit_remaining());
  }
}

void RateLimitResponse_DescriptorStatus::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RateLimitResponse_DescriptorStatus::CopyFrom(const RateLimitResponse_DescriptorStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RateLimitResponse_DescriptorStatus::IsInitialized() const {
  return true;
}

void RateLimitResponse_DescriptorStatus::Swap(RateLimitResponse_DescriptorStatus* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RateLimitResponse_DescriptorStatus::InternalSwap(RateLimitResponse_DescriptorStatus* other) {
  using std::swap;
  swap(current_limit_, other->current_limit_);
  swap(code_, other->code_);
  swap(limit_remaining_, other->limit_remaining_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RateLimitResponse_DescriptorStatus::GetMetadata() const {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RateLimitResponse_DescriptorStatus

// .pb.lyft.ratelimit.RateLimitResponse.Code code = 1;
void RateLimitResponse_DescriptorStatus::clear_code() {
  code_ = 0;
}
::pb::lyft::ratelimit::RateLimitResponse_Code RateLimitResponse_DescriptorStatus::code() const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus.code)
  return static_cast< ::pb::lyft::ratelimit::RateLimitResponse_Code >(code_);
}
void RateLimitResponse_DescriptorStatus::set_code(::pb::lyft::ratelimit::RateLimitResponse_Code value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus.code)
}

// .pb.lyft.ratelimit.RateLimit current_limit = 2;
bool RateLimitResponse_DescriptorStatus::has_current_limit() const {
  return this != internal_default_instance() && current_limit_ != NULL;
}
void RateLimitResponse_DescriptorStatus::clear_current_limit() {
  if (GetArenaNoVirtual() == NULL && current_limit_ != NULL) delete current_limit_;
  current_limit_ = NULL;
}
const ::pb::lyft::ratelimit::RateLimit& RateLimitResponse_DescriptorStatus::current_limit() const {
  const ::pb::lyft::ratelimit::RateLimit* p = current_limit_;
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus.current_limit)
  return p != NULL ? *p : *reinterpret_cast<const ::pb::lyft::ratelimit::RateLimit*>(
      &::pb::lyft::ratelimit::_RateLimit_default_instance_);
}
::pb::lyft::ratelimit::RateLimit* RateLimitResponse_DescriptorStatus::mutable_current_limit() {
  
  if (current_limit_ == NULL) {
    current_limit_ = new ::pb::lyft::ratelimit::RateLimit;
  }
  // @@protoc_insertion_point(field_mutable:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus.current_limit)
  return current_limit_;
}
::pb::lyft::ratelimit::RateLimit* RateLimitResponse_DescriptorStatus::release_current_limit() {
  // @@protoc_insertion_point(field_release:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus.current_limit)
  
  ::pb::lyft::ratelimit::RateLimit* temp = current_limit_;
  current_limit_ = NULL;
  return temp;
}
void RateLimitResponse_DescriptorStatus::set_allocated_current_limit(::pb::lyft::ratelimit::RateLimit* current_limit) {
  delete current_limit_;
  current_limit_ = current_limit;
  if (current_limit) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus.current_limit)
}

// uint32 limit_remaining = 3;
void RateLimitResponse_DescriptorStatus::clear_limit_remaining() {
  limit_remaining_ = 0u;
}
::google::protobuf::uint32 RateLimitResponse_DescriptorStatus::limit_remaining() const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus.limit_remaining)
  return limit_remaining_;
}
void RateLimitResponse_DescriptorStatus::set_limit_remaining(::google::protobuf::uint32 value) {
  
  limit_remaining_ = value;
  // @@protoc_insertion_point(field_set:pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus.limit_remaining)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RateLimitResponse::kOverallCodeFieldNumber;
const int RateLimitResponse::kStatusesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RateLimitResponse::RateLimitResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.lyft.ratelimit.RateLimitResponse)
}
RateLimitResponse::RateLimitResponse(const RateLimitResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      statuses_(from.statuses_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  overall_code_ = from.overall_code_;
  // @@protoc_insertion_point(copy_constructor:pb.lyft.ratelimit.RateLimitResponse)
}

void RateLimitResponse::SharedCtor() {
  overall_code_ = 0;
  _cached_size_ = 0;
}

RateLimitResponse::~RateLimitResponse() {
  // @@protoc_insertion_point(destructor:pb.lyft.ratelimit.RateLimitResponse)
  SharedDtor();
}

void RateLimitResponse::SharedDtor() {
}

void RateLimitResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RateLimitResponse::descriptor() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RateLimitResponse& RateLimitResponse::default_instance() {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::InitDefaults();
  return *internal_default_instance();
}

RateLimitResponse* RateLimitResponse::New(::google::protobuf::Arena* arena) const {
  RateLimitResponse* n = new RateLimitResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RateLimitResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.lyft.ratelimit.RateLimitResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  statuses_.Clear();
  overall_code_ = 0;
  _internal_metadata_.Clear();
}

bool RateLimitResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.lyft.ratelimit.RateLimitResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .pb.lyft.ratelimit.RateLimitResponse.Code overall_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_overall_code(static_cast< ::pb::lyft::ratelimit::RateLimitResponse_Code >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus statuses = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_statuses()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.lyft.ratelimit.RateLimitResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.lyft.ratelimit.RateLimitResponse)
  return false;
#undef DO_
}

void RateLimitResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.lyft.ratelimit.RateLimitResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .pb.lyft.ratelimit.RateLimitResponse.Code overall_code = 1;
  if (this->overall_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->overall_code(), output);
  }

  // repeated .pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus statuses = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->statuses_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->statuses(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.lyft.ratelimit.RateLimitResponse)
}

::google::protobuf::uint8* RateLimitResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pb.lyft.ratelimit.RateLimitResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .pb.lyft.ratelimit.RateLimitResponse.Code overall_code = 1;
  if (this->overall_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->overall_code(), target);
  }

  // repeated .pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus statuses = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->statuses_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->statuses(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.lyft.ratelimit.RateLimitResponse)
  return target;
}

size_t RateLimitResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.lyft.ratelimit.RateLimitResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus statuses = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->statuses_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->statuses(static_cast<int>(i)));
    }
  }

  // .pb.lyft.ratelimit.RateLimitResponse.Code overall_code = 1;
  if (this->overall_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->overall_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RateLimitResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.lyft.ratelimit.RateLimitResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const RateLimitResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RateLimitResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.lyft.ratelimit.RateLimitResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.lyft.ratelimit.RateLimitResponse)
    MergeFrom(*source);
  }
}

void RateLimitResponse::MergeFrom(const RateLimitResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.lyft.ratelimit.RateLimitResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  statuses_.MergeFrom(from.statuses_);
  if (from.overall_code() != 0) {
    set_overall_code(from.overall_code());
  }
}

void RateLimitResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.lyft.ratelimit.RateLimitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RateLimitResponse::CopyFrom(const RateLimitResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.lyft.ratelimit.RateLimitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RateLimitResponse::IsInitialized() const {
  return true;
}

void RateLimitResponse::Swap(RateLimitResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RateLimitResponse::InternalSwap(RateLimitResponse* other) {
  using std::swap;
  statuses_.InternalSwap(&other->statuses_);
  swap(overall_code_, other->overall_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RateLimitResponse::GetMetadata() const {
  protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_source_2fcommon_2fratelimit_2fratelimit_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RateLimitResponse

// .pb.lyft.ratelimit.RateLimitResponse.Code overall_code = 1;
void RateLimitResponse::clear_overall_code() {
  overall_code_ = 0;
}
::pb::lyft::ratelimit::RateLimitResponse_Code RateLimitResponse::overall_code() const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitResponse.overall_code)
  return static_cast< ::pb::lyft::ratelimit::RateLimitResponse_Code >(overall_code_);
}
void RateLimitResponse::set_overall_code(::pb::lyft::ratelimit::RateLimitResponse_Code value) {
  
  overall_code_ = value;
  // @@protoc_insertion_point(field_set:pb.lyft.ratelimit.RateLimitResponse.overall_code)
}

// repeated .pb.lyft.ratelimit.RateLimitResponse.DescriptorStatus statuses = 2;
int RateLimitResponse::statuses_size() const {
  return statuses_.size();
}
void RateLimitResponse::clear_statuses() {
  statuses_.Clear();
}
const ::pb::lyft::ratelimit::RateLimitResponse_DescriptorStatus& RateLimitResponse::statuses(int index) const {
  // @@protoc_insertion_point(field_get:pb.lyft.ratelimit.RateLimitResponse.statuses)
  return statuses_.Get(index);
}
::pb::lyft::ratelimit::RateLimitResponse_DescriptorStatus* RateLimitResponse::mutable_statuses(int index) {
  // @@protoc_insertion_point(field_mutable:pb.lyft.ratelimit.RateLimitResponse.statuses)
  return statuses_.Mutable(index);
}
::pb::lyft::ratelimit::RateLimitResponse_DescriptorStatus* RateLimitResponse::add_statuses() {
  // @@protoc_insertion_point(field_add:pb.lyft.ratelimit.RateLimitResponse.statuses)
  return statuses_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::lyft::ratelimit::RateLimitResponse_DescriptorStatus >*
RateLimitResponse::mutable_statuses() {
  // @@protoc_insertion_point(field_mutable_list:pb.lyft.ratelimit.RateLimitResponse.statuses)
  return &statuses_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::lyft::ratelimit::RateLimitResponse_DescriptorStatus >&
RateLimitResponse::statuses() const {
  // @@protoc_insertion_point(field_list:pb.lyft.ratelimit.RateLimitResponse.statuses)
  return statuses_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ratelimit
}  // namespace lyft
}  // namespace pb

// @@protoc_insertion_point(global_scope)
