FROM ubuntu:xenial
RUN apt-get update \
  && apt-get install -y iptables curl

# TODO: customize the version
ADD istio-proxy_amd64.deb /tmp

RUN dpkg -i /tmp/istio-proxy_amd64.deb && rm /tmp/istio-proxy_amd64.deb