cc_library(
    name = "rapidjson",
    hdrs = glob(["rapidjson/include/**/*.h"]),
    includes = ["rapidjson/include"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "backward",
    srcs = ["backward/backward.cpp"],
    hdrs = [
        "backward/backwards.hpp",
    ],
    visibility = ["//visibility:public"],
)
