# Custom envoy configuration for simple zvpn.
# Work in progress to automate it by having Pilot generate LDS v2 with SNI and capture the zvpn ports from
# annotations.
apiVersion: v1
kind: ConfigMap
metadata:
  name: zvpn-envoy-config
  namespace: istio-system
data:
  envoy.yaml: |
    stats_config:
      # Without this option it create a lot of regex, may run out of space.
      use_all_default_tags: false

    admin:
      access_log_path: /dev/stdout
      address:
        # Only allow debugging from localhost
        socket_address: { address: 127.0.0.1, port_value: 15000 }

    dynamic_resources:
      # LDS is not currently enabled, once SNI is enabled and LDSv2 ready, it will replace the manual config.
      lds_config:
        api_config_source:
          api_type: REST_LEGACY
          refresh_delay: 10s
          cluster_names: [rds]
      cds_config:
         api_config_source:
            api_type: REST_LEGACY
            refresh_delay: 10s
            cluster_names: [rds]
      deprecated_v1:
        sds_config:
          api_config_source:
                api_type: REST_LEGACY
                refresh_delay: 10s
                cluster_names: [rds]

    static_resources:
      listeners:

      - name: tcp-zvpn-pilot
        address:
          socket_address: { address: 0.0.0.0, port_value: 15003 }
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              deprecated_v1: true
              value:
                stat_prefix: tcp_pilot
                route_config:
                    routes:
                    - cluster: zvpn.pilot

      - name: tcp-zvpn-mixer
        address:
          socket_address: { address: 0.0.0.0, port_value: 15006 }
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              deprecated_v1: true
              value:
                stat_prefix: tcp-mixer
                route_config:
                    routes:
                    - cluster: zvpn.mixer

      - name: tcp-zvpn-ca
        address:
          socket_address: { address: 0.0.0.0, port_value: 8060 }
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              deprecated_v1: true
              value:
                stat_prefix: tcp_ca
                route_config:
                    routes:
                    - cluster: zvpn.ca

{{- range $app := .Values.zvpn.apps }}
      - name: tcp-zvpn-{{ $app.portName }}
        address:
          socket_address: { address: 0.0.0.0, port_value: {{ $app.externalPort }} }
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              deprecated_v1: true
              value:
                stat_prefix: {{ $app.portName }}
                route_config:
                    routes:
                    - cluster: zvpn.{{ $app.portName }}
{{ end }}

      clusters:
      - name: rds
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        hosts:
          # TODO(costin): add TLS/15003
          - { socket_address: { address: "istio-pilot.istio-system", port_value: 8080 }}

      # Direct zvpn connection to pilot TLS port. This is used with a TCP proxy !
      - name: zvpn.pilot
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        hosts:
          - { socket_address: { address: "istio-pilot", port_value: 15003 }}

      - name: zvpn.ca
        connect_timeout: 0.25s
        lb_policy: ROUND_ROBIN
        type: EDS
        eds_cluster_config:
          service_name: istio-ca.istio-system.svc.cluster.local|grpc
          eds_config:
            api_config_source:
              api_type: REST_LEGACY
              cluster_names: [rds]
              refresh_delay: 10s

      # Connection to Mixer.
      - name: zvpn.mixer
        connect_timeout: 0.25s
        lb_policy: ROUND_ROBIN
        type: EDS
        eds_cluster_config:
          service_name: istio-mixer.istio-system.svc.cluster.local|grpc
          eds_config:
            api_config_source:
              api_type: REST_LEGACY
              cluster_names: [rds]
              refresh_delay: 10s

{{- range $app := .Values.zvpn.apps }}

      - name: zvpn.{{ $app.portName }}
        connect_timeout: 0.25s
        lb_policy: ROUND_ROBIN
        type: EDS
        eds_cluster_config:
          service_name: {{ $app.serviceKey }}
          eds_config:
            api_config_source:
              api_type: REST_LEGACY
              cluster_names: [rds]
              refresh_delay: 10s
{{ end }}
---
